name: goreleaser

on:
  push:
    branches:
      - main

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  tag-bump:
    name: bump tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        id: check-out
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Github Tag Bump
        id: tag-bump
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: true
          RELEASE_BRANCHES: main
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
